### ISSUE TITLE
Enable spaces in keyword tags

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1055]
As the title suggests.

Server issue: https://github.com/OpenBazaar/OpenBazaar-Server/issues/284

**Comment by morebrownies** [comment]
I don't understand this request. Why would a tag allow spaces? I've never seen that on any other platform.

**Comment by mariodian** [comment]
I've seen spaces in tags mostly on blogging platforms. For example tumblr.com allows it.

**Comment by drwasho** [comment]
> I've never seen that on any other platform.

I think it adds some flexibility to tags considering that we can't search for multiple tags.

**Comment by morebrownies** [comment]
It actually makes matching more difficult because users will need to get the spaces correctly. Some people will tag #blueHondaCivic and others will tag #blue honda civic and both will return unique results because they're different tags. If we trim the spaces for the user, those tags both become the same.

**Comment by drwasho** [comment]
Yeah you have a point there. If for no other reason than Instagram and Instagram are the standards for setting expectations for tagging.
