### ISSUE TITLE
Different color text to speed workflow.(Somewhat important, but should be fairly easy)

### ISSUE THREAD

**Issue by beatljuice** [OpenBazaar/OpenBazaar-Client#1123]
Different colors of text would help to indicate what needs attention in Sales and Purchases.

When you have a list of things without much differentiation you have to read and think a lot more. If the things that need attention (such as paid/ready to ship, or mark received and release funds) on the list had a colored text that made it stand out you could get things done a lot faster.

**Comment by pryds** [comment]
When doing so, please don't exclude the 8% of all males who happen to be colour blind to some degree. Please, be very careful when you choose the colours to use for this.

A couple of informative articles:
http://designshack.net/articles/accessibility/tips-for-designing-for-colorblind-users/
http://understandinggraphics.com/design/designing-for-color-blindness/

**Comment by morebrownies** [comment]
I posted a solution for this on #874 

We could do something similar for newly disputed orders as well. Instead of the orange indicator, it would show a red indicator. Showing an indicator for new orders and disputed orders seems like the most important scenarios to support. I don't know if we have support for this in the API to know when an order is new and not viewed yet, same goes for disputed orders so we may need some backend changes in place first to know when to display the indicator. 

Also @pryds the color challenge isn't easy since people use custom themes. If you or anyone reading this is color blind, please choose a color palette that renders well with your eyes. :)

**Comment by pryds** [comment]
> If you or anyone reading this is color blind, please choose a color palette that renders well with your eyes. :)

Being able to choose which colours represent what is of course the best solution for any colour blind user, given representation has to be done with colours in the first place :-)

Anyway, I'm just mentioning this for devs to keep in the back of their minds, so they don't unintentionally block out a large percentage of user base from certain features.

**Comment by jjeffryes** [comment]
No vital information should use colors at all. Anything that you need to be able to see in order to use the client should be visible in greyscale, and in low contrast. 

We may want to add a setting to use a set of default styles that are friendly to people with visual impairments, and have that as an option in onboarding.

**Comment by SamPatt** [comment]
Current changes in the transactions page should resolve or make this issue obsolete, so I'm closing.
