### ISSUE TITLE
Indicate that the minimum local or international shipping price is 0.01 BTC

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#116]
At the moment it just gives you an error without explanation.

**Comment by drwasho** [comment]
Bump @morebrownies

**Comment by morebrownies** [comment]
This seems like a UX nightmare to me for a few reasons.

1) Most users will be setting prices in fiat, so displaying a min price of 0.01 BTC will just confuse them. If anything, we'll want to do the conversion and return back what the min price is in their local currency and not in bitcoin.

2) As of right now, 0.01 BTC = $4.06 USD. We're basically saying items under $5 aren't supported? Why?

3) If the price of 0.01 BTC rapidly spikes to let's say $10 USD, now items under $10 aren't supported. If I have items in my store that already have a set price of $8 and I go to edit them, I'll be forced to raise the price in order to submit the edits. 

I'm not sold on this. I think we need to rethink this restriction.

**Comment by hoffmabc** [comment]
0.01 is too high I agree with @morebrownies

**Comment by hoffmabc** [comment]
This isn't BitMarkets

**Comment by drwasho** [comment]
I submitted issue #121 to decrease the minimum price.

**Comment by hoffmabc** [comment]
Why not just amend this issue? Can you consolidate and close one?
