### ISSUE TITLE
Search URLs should be clickable in Chat

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1202]
Currently they're plain text 

<img width="357" alt="screenshot 2016-03-28 12 44 19" src="https://cloud.githubusercontent.com/assets/13066886/14084955/d516ab54-f4e2-11e5-9d67-70dacfc0a492.png">

**Comment by morebrownies** [comment]
Looks like there is a bug. 

<img width="267" alt="screenshot 2016-03-28 19 08 54" src="https://cloud.githubusercontent.com/assets/13066886/14094067/8bb071da-f518-11e5-86ac-1212579870b0.png">

**Comment by morebrownies** [comment]
I didn't add the extra ob://

**Comment by drwasho** [comment]
Seems to happen with me when you type `ob://#[tag]` => `ob://ob://#[tag]`

**Comment by jjeffryes** [comment]
The ob:// is required.

The internal links all start with #, so the code can't tell the difference between #bluedress and #userPage. 

I can see if I can think of a more clever way to deal with it, but for now the options are have ob:// in front of tags and have them be clickable, or not have ob:// and they can't be clicked.

I added it to the @ because it looked weird to only have it for one of them.

**Comment by jjeffryes** [comment]
Deleting previous comment, because I shouldn't check gitHub on mobile devices.

The extra ob:// is definitely a bug.
