### ISSUE TITLE
Expanded Shipping Options.

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1263]
This is a catch-all issue for the various concerns that have been raised for shipping options. Please leave comments here instead of opening new issues.

New shipping issues will be closed and directed to this issue.

**Comment by M45t3rJC** [comment]
Shipping and Processing Time using plain text #1180 

This sounds like a nice enhancement...
+1

**Comment by jjeffryes** [comment]
There are two parts to this issue. Shipping options in the listing, and addresses in the Settings section. 

Options suggested for the Listings include:
- different rates for each country shipped to
- more than one country considered local for local rates
- allowing multiple ship from locations
- having multiple shipping options like express, registered, etc.

Options suggested for the Addresses in Settings include:
- plain text, with no formatted shipping data at all (this would mean doing the same in the listing)
- adding GPS coordinates
- much more flexible fields or more fields

**Comment by TheButterZone** [comment]
https://github.com/OpenBazaar/OpenBazaar-Client/issues/905
https://github.com/OpenBazaar/OpenBazaar-Client/issues/1014

**Comment by TheButterZone** [comment]
For Listings:
- All time fields should be optional.
- Ships To should **not** be Worldwide by default, due to customs declarations that people like me refuse to swear under penalty of perjury (as ignorance, of more laws than any normal victimless human can comprehend or abide by, is no defense). Rather than X-ing Worldwide and using the carpal tunnel syndrome-exacerbating country search, there should be binary choice bubbles (like the free shipping bubbles) for Ships To Worldwide Yes or No, so if someone clicks No, the default choice auto-fills their country via geolocation based on IP or their address they entered in their settings (or just country could be asked for in the setup wizard and remembered for listings).
- Free Shipping - NO selection, should lead to a second set of binary choice bubbles - Flat rate shipping (which would reveal the current shipping price fields https://blog.openbazaar.org/wp-content/uploads/2016/02/createlistingshipping.png) OR Quote shipping (which would require the buyer to provide their shipping details - as specific as they want to be - in plaintext to the seller), who would then calculate and send the lowest possible shipping cost back to the buyer's order screen and add it to their total). The buyer could then accept and pay or reject the quote without penalty. If the seller sees the buyer is within driving distance, they could forgo shipping cost altogether and meet.

**Comment by jjeffryes** [comment]
This was closed in #1780
