### ISSUE TITLE
Server does not connect more when I open for the second time.

### ISSUE THREAD

**Issue by Anderson-Juhasc** [OpenBazaar/OpenBazaar-Client#1264]
Brief Description: After opening it again is just on screen again trying to connect to the server.

Operating System (OS and version): Ubuntu
Hardware: Intel® Core™ i7-4710MQ CPU @ 2.50GHz × 8 

Steps to reproduce:
1. First opened.
2. Close
3. Try open again

**Comment by JerzySpendel** [comment]
I think I have the same problem, but not sure if it failed to connect after second launch or even later.

**Comment by jjeffryes** [comment]
This appears to be a problem with the server eventually getting too bogged down and not responding to the client. PR #1266 should change the client so it eventually reaches the server instead of closing the connection, but the underlying problem with it taking a very long time will need to be fixed on the server.

**Comment by eddieoz** [comment]
After killing all instances inside bash and starting server manually, when loading the client it connects again.

`openbazaard start --loglevel debug`

Second time this issue occurs with me and I solved with that.
