### ISSUE TITLE
VAT should be supported

### ISSUE THREAD

**Issue by Morveus** [OpenBazaar/OpenBazaar-Client#1265]
Hi!

This issue is a bit linked to this one: https://github.com/OpenBazaar/OpenBazaar-Client/issues/1262
Companies need to apply different tax percentages (at least that's how it works in France and I guess some countries in the EU) depending on where the products are sent and annual volumes.

It is really important that the seller can specify if his listing price includes VAT (if I'm a company) or not (if I'm selling by myself), and tax rates by destination countries.

For instance, if we sell a Nano (listing price 29€) to a german customer, we need to apply the french 20% VAT which raises the cost to 34.80€.
The same Nano sent to the US will have a 0% VAT and will be sold at 29€ (US customs will take care of  taxes, you can count on them).

Also if I remember correctly, if the company sales exceed some value in a given destination country, destination VAT rates apply and have to be specified by country. 
For instance, we will have to sell the Nano for 29€ + 22% VAT (35.38€) in Italy some day, if our sales exceed 35k€ per year in this country. We'd then have to specify "22%" for "Italy" on our OpenBazaar listing in that case.

**Comment by gubatron** [comment]
oh European union, what a clusterfuck of a taxation system they have over there.
Very valid request though.

**Comment by drwasho** [comment]
Given that OpenBazaar is a global marketplace, we cannot be expected to add the complex tax laws for 190+ countries into the protocol.

**Comment by jjeffryes** [comment]
This does point to the usefulness of some kind of post-purchase additional fee negotiated for each transaction separately.

**Comment by btchip** [comment]
Yes, this is not to be added in the protocol (even if other global marketplaces such as Amazon or Ebay seem to be handling it gracefully), but merchants should at least be able to do something similar to what @jjeffryes suggested. Otherwise this will lead to many complaints as products will be held by customs, end users will be paying random additional fees, and likely both

**Comment by Morveus** [comment]
@drwasho Merchants are expected to know about and to follow those complex tax laws, not OpenBazaar of course.
I'm only talking about adding an optional "tax value" variable for each destination, that the seller enables only if he needs it. It would be like most e-commerce platforms.

**Comment by gubatron** [comment]
whatever the solution is, it must be a meta solution as tax laws like described by the OP can be really complex, it's not just having a tax per jurisdiction, but different rates depending on your sales volume too (Europe Taxation people, go home you're drunk)

**Comment by gubatron** [comment]
perhaps OpenBazaar needs to have a plugin framework, and like @jjeffryes said, this would be a great use-case for a post-purchase-plugin-hook, then let the free market develop a "European Taxation OpenBazaar Hookup" and let it be sold in the market place for European sellers. 

Like in Wordpress land, a plugin-appstore could be a great way for OB1 to monetize on its ecosystem.

**Comment by mariodian** [comment]
OB is all about the free market so I think we should keep the tax thing as simple as possible. It's like having bitcoin inflated by FEDs. I don't think this is our goal.

**Comment by Morveus** [comment]
I'm pretty sure it's not just a "EU-only" issue (see https://en.wikipedia.org/wiki/Value-added_tax). I was suggesting a really simple solution: let this seller set a custom tax rate by destination. 

Don't worry about the complexity of what I described in my first post, I was just explaining _why_ we need to be able to set custom rates, not suggesting that OB had to automate those calculations. If the seller reaches a certain volume for a certain country, he'll manually adjust the rate in OB.

**Comment by burdges** [comment]
As I understood it, there are laws against not merely failing to include the VAT in the advertised price, but also against adjusting the price based upon a change in the VAT @Morveus.  

If that's correct, then you cannot charge that 22% just to Italian customers anyways.  You must instead bake that possible +2% into your advertised price somehow.  If I'm wrong, then blame Amazon for interpreting EU laws in a way that makes merchants add that +2% all the time, and lets them pocket it when you sell to Germany.  ;) 

Assuming I'm right, then issues are not "per sale" but more "tax helper" docs or scripts that address questions like : How do I compute the expected VAT I should be charging based upon me expected buyers?  How do I extract the sales per country to compute the exact VAT I must pay at tax time?  Can I set some alarm so that if I sell to much to high VAT countries I can make adjustments?  etc.  

It's more about exporting data well than about a plugin framework per se.

**Comment by drwasho** [comment]
We've recently made some redesigns on the contract schema to allow users to factor in whatever tax they need to. I'm closing this issue for now as it will be a sprint item soon with a full set of requirements.
