### ISSUE TITLE
Filtering listings not obvious

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1278]
On the @helpdesk, about 20 people have asked why they are only seeing 4 listings. We tell them to try disabling "Filtered listings". Maybe the toggle needs to be emphasized somehow?

**Comment by jjeffryes** [comment]
The toggle has been emphasized in master, and will be much more obvious in the next release.

**Comment by mariodian** [comment]
I think this feature should be off by default. I don't see any case where somebody needs to only see items from stores he likes. 

Perhaps it could be decided in the installation process? If I wasn't using Slack I'd probably never find the filter.

**Comment by jjeffryes** [comment]
Currently, we default to only followed stores because we can't control what images are in listings, and we've had problems when testing where people would use OpenBazaar for the first time and see disturbing or inappropriate images. 

This is very much a temporary measure, long term we have significantly better solutions in the works.

**Comment by mariodian** [comment]
An image could be flagged and hidden by the user if he finds it offensive. But I'm looking forward to mentioned solutions.
