### ISSUE TITLE
Review(s) wording on item page under buy now button

### ISSUE THREAD

**Issue by valmassoi** [OpenBazaar/OpenBazaar-Client#1334]
If the number of reviews on an item is >1 change the word Review to Reviews. As it is now one of my items says 2 Review (5/5)

**Comment by rmisio** [comment]
This was something we had code in place to handle, but apparently having different word endings would make translating difficult, since different languages pluralize things in different ways. So we decided to just live with the incorrect grammar in English.

I suppose we could have separate plural and singular translations, which include a placeholder?? My guess is that would be flexible enough for all langs to handle. For example:

```
'review':  '%{count} review',
'reviews': '%{count} reviews',
```

There would be a bit of work to apply this to all similar relevant areas.

**Comment by SamPatt** [comment]
Thank you for the suggestion, but I don't think having a tab called "Reviews" which has 0 or 1 reviews is a problem. Amazon calls their section "Customer Reviews" regardless of the number. I'm closing.
