### ISSUE TITLE
Right click menu not showing

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1387]
Right click menu (with Undo, Cut, Copy, Past, Delete, Select All)  is not showing when right clicking any element on the OB software.

OB v1.1.3 Win 7 64 bits

**Comment by jjeffryes** [comment]
This appears to be due to the context menu being created with menu.setApplicationMenu(appMenu) in main.js.

For Windows and Linux, I believe that would attach it to the top menu, which we are hiding. 

It should be changed to be activated when right clicking, using the contextmenu event. 

https://github.com/electron/electron/blob/master/docs/api/menu.md#menusetapplicationmenumenu

**Comment by jjeffryes** [comment]
This was closed in #1506
