### ISSUE TITLE
Feature request: As a vendor I should be able to cancel an order

### ISSUE THREAD

**Issue by kabo** [OpenBazaar/OpenBazaar-Client#1390]
Brief Description: 
As a vendor I should be able to cancel an order.

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.3
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Buyer places an order
2. Buyer changes his mind and doesn't pay
3. 

Observed Behavior:
As a vendor I'm unable to cancel the order

Expected Behavior:
As a vendor I should be able to cancel the order

Additional info (links, images, etc go here):

**Comment by SamPatt** [comment]
In the latest client, we now hide orders which have been unfunded by default.

![image](https://cloud.githubusercontent.com/assets/6955773/15587429/34ff0afa-2357-11e6-8cd1-bc5c1f73d222.png)

The reason we don't allow deleting an order is that if a buyer changes the mind again and does fund it, then the vendor will never even know that happened and the funds will be lost. Since it is annoying to vendors to see those unfunded abandoned orders the compromise is to simply hide the orders from view, unless you are specifically looking for them and then you can hit the "Show Unfunded" button.

I'm closing this issue.
