### ISSUE TITLE
UI issue: overlay background gradient blocks window management controls

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1449]
On this screen there isn't a way to close, minimize or maximize the window because the overlay background is covering them. We should ensure that these controls are always accessible throughout the experience. 

<img width="1220" alt="screenshot 2016-04-26 12 47 53" src="https://cloud.githubusercontent.com/assets/13066886/14832097/5368d622-0bad-11e6-823e-e980763d025b.png">

**Comment by jjeffryes** [comment]
That could be complicated, since we don't want the user to be trying to navigate to other parts of the app when the loading overlay is visible (it's only visible when in the middle of loading something). 

Off the top of my head, we'd have to break those controls out into their own view and template, and build them separately from the pageNav view. Which could cause some other issues. 

Or duplicate them in the loading overlay.

**Comment by morebrownies** [comment]
Right. The big problem is users can't minimize their window (or close it) if they're not connected to a server, which is very annoying. I just ran into this myself and had the urge to start throwing objects :)

**Comment by jjeffryes** [comment]
Can't you still close it from the tray icon?

**Comment by morebrownies** [comment]
Yeah, you can, but it's bad practice to cover window controls in app. It's a big no no for native apps.

**Comment by jjeffryes** [comment]
I'm not disagreeing, I just wanted to make sure the close control wasn't missing in the tray on Macs.

**Comment by jjeffryes** [comment]
Completed.
