### ISSUE TITLE
Snapchat not super popular with vendors

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1502]
Below is the list of all Snapchat entries for vendors as seen by www.duosear.ch. There are 12 "garbage" entries and only 12 valid entries. Should we remove Snapchat altogether?

```
-
encrypted WTF...
mariodian
jcom3030
test s
bitcoin13
http://bazaarbay.org/1fcb9a8beb32f688fef7b61a52d091b9dd8c1f27
cryptortrust
what the fucking fuck is snapflaps?
n/a
What the fucking fuck?
That neither.
N/A

nathanhawkeye
bitmall.org
TexasBitcoin
mrgregmoon


NA
rhythmnpoetry
danishbitweed
onurgozupek
gcaccess
```

**Comment by hoffmabc** [comment]
I actually think the prudent thing might be to just pull in Blockchain ID social accounts and not manage it at all. @drwasho @jjeffryes @morebrownies

**Comment by jjeffryes** [comment]
We'll have to think about that, since that would mean anyone that hasn't added those social accounts to their Blockchain ID, or that doesn't want to use Blockchain ID can't add social accounts.

If we think they're low-value, then that'd be fine.

**Comment by mariodian** [comment]
I don't think that's a good idea because lot of people can't get their onename handles verified for ages. In my case it was several weeks.

**Comment by morebrownies** [comment]
Agreed. We should let the user manage the social network links within app because not everyone necessarily wants a handle.

I think we need to expand on how it works though. We hard-coded a bunch of social networks that make sense to us, but they don't necessarily make sense to someone in China or Japan. Also, some people may want to link to their eBay store or Etsy store and they have no way of doing that other than adding it to their about section. 

What I'm thinking is we make the right column more flexible so that users can add whatever they'd like. I'll put some design together for what I'm thinking.

**Comment by jjeffryes** [comment]
We're not planning to change this in v1, v2 will handle social links differently.
