### ISSUE TITLE
Make Zip code optional

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1680]
Some locations don't have a zip code, but the application is assuming all delivery addresses do. This should be an optional component of the shipping address. This is one idea of how to represent that:

![image](https://cloud.githubusercontent.com/assets/3887694/15883983/7726402c-2d90-11e6-9bc9-8846ca714f1a.png)

I'll make a parallel server issue.

**Comment by Gitju** [comment]
Also somehow it is irritating that a complete address is necessary to see if the delivery into a country is possible despite the fact that the country matches.

During the install I setup my country. Then when I find an article that delivers to my country I just see the information that it does not deliver to my country.

First I must insert a complete delivery address and then it shows that delivery to my country is possible.

For this decision just the country would be necessary.

**Comment by jjeffryes** [comment]
@Gitju it should pick up your country when determining if the product will ship to you.

Where did you see the message that the product will not ship to your country?

**Comment by Gitju** [comment]
Here is a listed article that ships to **Deutschland** (Germany) but it shows that no one of my addresses are in a country where this article can be send to.

![keine](https://cloud.githubusercontent.com/assets/5765500/15952388/ae91bba0-2ec0-11e6-92ac-5fc08feed280.png)

This is my actual address tab after a fresh installation where the country is set to **Deutschland**.

![adresse](https://cloud.githubusercontent.com/assets/5765500/15952501/a2f2a966-2ec1-11e6-8cbf-c46cf013dbf2.png)

As a new user I don't expect that I need to setup a full address at first to then be able to see if an article can be send to me because the country is already given in my address tab after I was asked for it during the installation.

**Comment by jjeffryes** [comment]
I see. 

The message is saying that none of your currently saved addresses can be shipped to, which is correct if you haven't saved any addresses yet.

It should say that you need to add an address, and that you can do so after clicking the buy button.

We'll update the language.

**Comment by ghost** [comment]
I disagree. For this part ("Can Ship to You In:"), OpenBazaar should consider user's country as his home "address", until he adds an address.
Most part of users will set their countries on the same place of their addresses, so it's not a problem.

**Comment by Gitju** [comment]
As a new user I would exactly expect what @rhcastilhos said.

**Comment by jjeffryes** [comment]
You're misunderstanding me, @rhcastilhos. Another part of the page already uses the country to match whether the product can be shipped to the user. The specific message being asked about is only for the address that is saved, and it should be clear about that fact.

Some users have a country that is different than the address they want something shipped to, so we need to cover that possibility, but make the message easier to understand.

**Comment by jjeffryes** [comment]
This was closed by #1780
