### ISSUE TITLE
Updating Country

### ISSUE THREAD

**Issue by emgra** [OpenBazaar/OpenBazaar-Client#1740]
Brief Description: Country to United Kingdom in error. I later corrected it to United States. It has updated correctly in Open Bazaar, however Duo and other search engines still show United Kingdom after a few days. They believe the problem is on your side.

I believe other users have the same problem. Can you please fix this as it is misleading to customers wanting to buy.

OpenBazaar version 1.1.7

Reproducible (Always)

Steps to reproduce:
Just look at the attached images.

Additional info (links, images, etc go here):
![duo](https://cloud.githubusercontent.com/assets/20304015/16592079/e0b15bac-42d6-11e6-85e4-112bd125bba0.png)
![how](https://cloud.githubusercontent.com/assets/20304015/16592093/ee932e80-42d6-11e6-9d6b-8fcf91001b37.png)

Thank You

**Comment by jjeffryes** [comment]
@emgra your country cannot be read by 3rd parties. It's only available via the settings API, which only your own client and node can use.

We don't know what data 3rd parties are using to determine your country. If they are using the depreciated location value in the profile API, they will need to remove that, since that value isn't used any more.

**Comment by jjeffryes** [comment]
I'm closing this issue, as the data involved has been depreciated. Duosearch is aware of that, and will be adjusting how they detect nodes' country of origin.
