### ISSUE TITLE
Could updating a contract cause trade problems?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#182]
Any updates to a contract will change the contract ID. What happens if the vendor updates a contract while a buyer has already begun the process of buying the product, or if funds are in multisig already?

I put this in Client repo but it affects both repos so we'll need @cpacia's opinion as well.

**Comment by cpacia** [comment]
> What happens if the vendor updates a contract while a buyer has already begun the process of buying the product

The buying process is unaffected. It would only be a problem if the vendor changes the contract after the buyer clicks buy but before the purchase message is sent to the vendor. And all that would happen is the vendor would reject the purchase because the contract hash buyer is trying to purchase no longer exists. So the buyer would have to back out and try again. 

But we don't want to put flags in the contract like Mike suggested. It would be wasteful.
