### ISSUE TITLE
Inventory tracking does not remember the number of items when creating new item

### ISSUE THREAD

**Issue by jooray** [OpenBazaar/OpenBazaar-Client#1870]
Brief Description: Creating new item, I enable inventory tracking and enter "1" as number of items. I click save. Then I click close and it says that changes are not saved. I cancel, save again and I see that the number of items is 0 again. I change back to one, click save, close and everything works

Operating System (OS and version): macOS 10.13
OpenBazaar version (shown on `About OpenBazaar` page in menu): client 2.0.14, server 0.9.3
Hardware: old mac mini

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create new item, fill everything, enable inventory tracking
2. enter "1" as number of items in inventory
3. Click save. Then I click close and it says that changes are not saved
4. I cancel, save again and I see that the number of items is 0 again.
5. I change back to one, click save, close and everything works

Observed Behavior: Number of items is not remembered the first time after creating an item

Expected Behavior: I click save and close and the number of items is remembered

Additional info (links, images, etc go here):

**Comment by rmisio** [comment]
This is the v1 repo. I assume you meant this for the [v2 repo](https://github.com/OpenBazaar/openbazaar-desktop)?

**Comment by rmisio** [comment]
In any case, I'm not able to reproduce this. I think it may have been fixed already, but the fix has not been released yet. When it's ready (2.0.15 or greater), feel free to give it a try. If it's still happening, go ahead and log the bug in the [v2 repo](https://github.com/OpenBazaar/openbazaar-desktop).

FWIW, since you're on OSX, your app should auto-update when the release is ready. You'll see a pop-up.
