### ISSUE TITLE
Settings - Cancel Button

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#220]
When the cancel button is pressed, nothing happens. It should go back to the home page.

**Comment by morebrownies** [comment]
I'm going to change the buttons around a bit today. I don't like the
current placement of them; they seem out of place and should be integrated
into the bottom of the form instead of in the title bar. We may not even
need a cancel button, just a simple save may be all that's needed.

I'm going to change them around today and then we can circle back to see if
any other changes are needed.

**Comment by drwasho** [comment]
Pressing cancel just reloads the settings page. Do we still need a cancel button? I know 
@hoffmabc had an issue with the name 'Cancel' if we keep it. I suggest we probably remove it... if people want to cancel stuff, they can go back home or refresh or something.

**Comment by jjeffryes** [comment]
I could see switching it to be a restore button or something.

**Comment by drwasho** [comment]
Yep that's a good idea.
