### ISSUE TITLE
Settings Page Issues

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#262]
- Page loads super slow not sure why.
- What does cancel do? Doesn't seem consistent.
- Avatar cropper shows nothing by default and gives impression no avatar is set.
- Bitcoin address has no validation (just length) so I can enter bullshit here.
- New Address should probably be at top because if I have a ton of addresses it will be hidden at the bottom of the page.

**Comment by drwasho** [comment]
- Page loads super slow not sure why. `still a issue`
- What does cancel do? Doesn't seem consistent. `still a issue`
- Avatar cropper shows nothing by default and gives impression no avatar is set. `still an issue`
- Bitcoin address has no validation (just length) so I can enter bullshit here. `limited validation`
- ~~New Address should probably be at top because if I have a ton of addresses it will be hidden at the bottom of the page.~~

**Comment by djbooth007** [comment]
Additionally:
- Cover photo cropper shows nothing when one has been uploaded and gives impression no cover is set.
- With theme of white background, anything typed into 'About' field is invisible (text is white).
