### ISSUE TITLE
Viewing an offline store takes user to blank default page

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#361]
Usability enhancement, when user clicks on an offline store, a message is displayed 'Data could not be retrieved' and user is sent to a blank default page.

Ideally, the user would receive a more friendly message popup (perhaps "This store is currently unavailable.") and the user would not be taken to a default page. They will remain on the initial page.

**Comment by morebrownies** [comment]
Agreed, the current experience is less than ideal. It's on my list to fix.

**Comment by morebrownies** [comment]
Here are designs for the desired experience.

1) When the connection is trying to be established, display some text showing who you're trying to connect to and provide a cancel button if the user wants to cancel the request because it's taking too long.

![openbazaar-failed-connection](https://cloud.githubusercontent.com/assets/13066886/12397338/31bf0740-bdd2-11e5-8463-d6ea23ef11c9.png)

2) When/if the connection fails, display a message saying the connection failed and provide a cancel button and a try again button. Clicking cancel takes the user back to where they were and clicking try again attempts to connect to the user again.

![openbazaar-failed-connection-retry](https://cloud.githubusercontent.com/assets/13066886/12397371/6cf2b0f0-bdd2-11e5-95ee-e09650038bd3.png)

Any one interested in taking this on? @zhuol?

**Comment by morebrownies** [comment]
@jjeffryes can we give this one to Rob?

**Comment by jjeffryes** [comment]
@morebrownies probably.Depends on other critical things getting done.

**Comment by morebrownies** [comment]
Was this task completed @drwasho? I haven't seen it in action yet.

**Comment by jjeffryes** [comment]
This has been updated so it takes the user back to the view they were on before trying to reach the offline instead of showing them the error message.
