### ISSUE TITLE
Pages or stores?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#429]
In the screenshot below, there is a screen listing "Pages". At the same time, I'm prompted to search for "stores". What is the difference between pages and stores? Can a store have many pages? (It seems that on my personal store I only have one page, labelled "My Page".)

![screen shot 2015-12-22 at 10 27 52](https://cloud.githubusercontent.com/assets/731743/11953272/c4f644f2-a896-11e5-8924-32f6b7338f42.png)

**Comment by cpacia** [comment]
I think the idea is to be able to view the pages of users besides just stores (ex buyers). Problem is there isn't any good way to get a list of everyone in the network. It would probably be better just being labeled stores IMO.

**Comment by JustinDrake** [comment]
Agreed. Stores feel more semantically meaningful than pages.

**Comment by morebrownies** [comment]
Some nodes will only offer "Moderator services", some will be "Stores", others will be "basic users" and some will be all 3. We need a single high level term that can reference all 3 different types. "Stores" doesn't work here because there are other pages in the network that need to be accessible in discover mode. 

Also, "check out my Page on OpenBazaar" — is something a store, moderator or basic user could say to their friends. 

As of now, we use the term "Page" all over the place:

<img width="303" alt="screenshot 2015-12-22 10 01 46" src="https://cloud.githubusercontent.com/assets/13066886/11959505/4b57ec20-a893-11e5-8abc-c13d720958ec.png">
<img width="1000" alt="screenshot 2015-12-22 10 03 01" src="https://cloud.githubusercontent.com/assets/13066886/11959504/4b559326-a893-11e5-985c-8fbbe8f3dafc.png">
<img width="1068" alt="screenshot 2015-12-22 10 03 36" src="https://cloud.githubusercontent.com/assets/13066886/11959506/4b5a2710-a893-11e5-8d9c-edf7dd4a1abe.png">
<img width="672" alt="screenshot 2015-12-22 10 09 42" src="https://cloud.githubusercontent.com/assets/13066886/11959659/241c87f0-a894-11e5-81da-85173904de48.png">

@drwasho please chime in, I know you've put a lot of thought to this as well.

Also, it appears that a recent change messed up the filter drop down on the "Pages" tab. The options should be "Stores", "Moderator services" and "Basic users", not "Stores I follow" and "All stores".

**Comment by JustinDrake** [comment]
@morebrownies: That makes sense. I imagine that, over time, clients will specialise to cater for one specific population: buyers, sellers or moderators. At this stage, having all three together is understandable, but somewhat awkward.

**Comment by cpacia** [comment]
My thinking is that most users will not want to see other buyers (there's almost nothing there to look at and the list will be woefully incomplete and most will be offline anyway). 

They might want to see moderators, but there are also other parts of the app where they can find moderators.

And they definitely want to see stores. 

So the term pages lumps all three together whereas the weight of what it's used for is only stores.

**Comment by morebrownies** [comment]
Agreed. I had the select dropdown defaulted to "stores" because of the same logic. If they do not care to see the other types, they could just ignore the dropdown. No harm in having them in there though.

**Comment by drwasho** [comment]
We're also future proofing here because the role of users that have a permanent online presence but aren't stores will emerge as we roll out the Feed and other social features. 

I agree with Wolf that defaulting to Stores is a **must** to fit with the most popular use case.
