### ISSUE TITLE
Navigation arrows shown in "unclickable" state

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#453]
Navigation arrows usually have two states: clickable and non-clickable (e.g. greyed out). See Chrome arrows below:

![screen shot 2016-01-04 at 23 38 51](https://cloud.githubusercontent.com/assets/731743/12103695/5464e4d6-b33c-11e5-9a4e-181b137e5503.png)

In the OB client, the arrows always seem to be greyed out (unclickable). They don't change state depending on whether or not there is history to navigate to.

![screen shot 2016-01-04 at 23 39 49](https://cloud.githubusercontent.com/assets/731743/12103705/776ac752-b33c-11e5-9547-0f0ef0eb7f69.png)

**Comment by drwasho** [comment]
Have you checked this on the `misc` branch of the client?

**Comment by JustinDrake** [comment]
@drwasho: No. What is the intent of the `misc` branch? When should I use it?

**Comment by morebrownies** [comment]
This hasn't been resolved in _misc_. Going to need @jjeffryes help on this one.

**Comment by drwasho** [comment]
Bump @morebrownies

**Comment by jjeffryes** [comment]
I'm removing the bug label, since this isn't really a bug, it's a request for an enhancement.

Rob and I discussed this at some length, neither Backbone nor the Chromium browser provides easy access to the data we'd need.

We can add our own code to keep track of all the route changes, and were you are on that list, but it's a bit of work.

**Comment by drwasho** [comment]
Thoughts on whether we really need this @morebrownies @jjeffryes @rmisio ?

**Comment by morebrownies** [comment]
Yes we need this fixed. Not a big deal if it doesn't make it into v1.
