### ISSUE TITLE
Minimum Bitcoin price

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#474]
In Bitcoin, the OpenBazaar minimum price is 0.0001 BTC. For Euros, the minimum price is 0.01 EUR.

These minimums are:
- Inconsistent (0.0001 BTC != 0.01 EUR)
- Somewhat arbitrary
- Not future proof (what if the price of Bitcoin balloons?)
- Not microtransaction-friendly

Bitcoin has a natural minimum price (namely, one satoshi). Why have a Bitcoin minimum price?

**Comment by drwasho** [comment]
> Inconsistent (0.0001 BTC != 0.01 EUR)

Yep, we should fix that @jjeffryes (low priority).

> Somewhat arbitrary

No, it's targeted to be close to the miner's fee (Bitcoin one at least).

> Not future proof (what if the price of Bitcoin balloons?)

If so, we'll update the client.

> Not microtransaction-friendly

If the Bitcoin price is less than the miner's fee, then the chance of having a transaction in limbo is too high. Microtransactions in OpenBazaar (like micropayment channels) need to be connected to a wallet built into the client, which is not targeted for v1.0. Also the dust limit is the _natural_ limit.

**Comment by jjeffryes** [comment]
This is set this way because (for example), the smallest denomination of USD currency is 0.01. There is no such thing as less than 0.01 USD in common usage (yes, for banks and financial institutions you can have fractions of a penny, but not in normal eCommerce). 

The simple solution is if you want prices in BTC, you should switch your currency to BTC.

**Comment by drwasho** [comment]
Boom

**Comment by JustinDrake** [comment]
@drwasho What does 'Boom' mean? Has anything changed? If so, can you link to a commit?
