### ISSUE TITLE
Search is essentially limited to 1 keyword

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#511]
I tried search for multiple keywords attached to my listings (e.g. `dress vintage`), but a space between the words does not delimit the terms I'm searching for (i.e. the client looks for `dress vintage` instead of `dress` `vintage`) and therefore fails. 

I suggest that adding search terms behaves like adding keywords to a contract in terms of UI/UX.

**Comment by hoffmabc** [comment]
Can you clarify here? Your description is too vague. So you enter dress, hit enter and it tokenizes, then you enter vintage, and it tokenizes and you can only find it by searching for "dress vintage" all one search term?

**Comment by jjeffryes** [comment]
This is a limitation of the API, it only accepts a single term.

**Comment by BazaarBay** [comment]
External search services can give more advanced listing search options. And, or, not, from specified vendor, not from specified vendor, using specified moderator, shipping to or from and so on.

**Comment by hoffmabc** [comment]
Oh yeah?? Like who? :)

**Comment by drwasho** [comment]
@cpacia can you make search API search multiple keyword?

**Comment by morebrownies** [comment]
@drwasho would this be an AND or an OR search? 

AND = If I search `dress` and `pink` I would only see listings that have both `dress` or `pink` tagged.
OR = If I search `dress` and `pink` I would see listings that have either `dress` or `pink` tagged, but not necessarily both.

**Comment by drwasho** [comment]
![why not both](https://cloud.githubusercontent.com/assets/3887694/12390235/f1709552-be29-11e5-808c-4a7368c5207f.jpg)

**Comment by morebrownies** [comment]
Does that mean AND? lol

**Comment by hoffmabc** [comment]
If you do OR then you will catch all three conditions. A, B and those that have both A and B.

**Comment by morebrownies** [comment]
Sure, but it would return a different set of results. For example, if I first search for `dress`, I see a bunch of dresses. If I add `pink` as a second keyword, I now see a bunch of dresses and pink things, but not necessarily pink dresses. 

AND helps filter down the search more where as OR broadens the search more.

**Comment by BazaarBay** [comment]
BazaarBay defaults to AND and also allows NOT using -word syntax like Google.

**Comment by drwasho** [comment]
For v1 I suggest we go with `AND`; we can add more complex search capabilities later.

**Comment by JustinDrake** [comment]
As an outsider looking onto OpenBazaar, and I mean no offence to the developpers, the OpenBazaar team may be moving in a wrong direction regarding search.

The bulk of an OpenBazaar client can be built to a high standard by an enthusiastic, well-rounded and talented team of developers because it's "easy". DHTs, listings, reviews, Bitcoin multisig, store customisation, etc. are fairly simple. On the other hand, search is a highly complex world of its own that needs specific expertise.

Having OpenBazaar implement its own search from scratch without expertise is (to me) crazy. My intuition tells me that the end user will necessarily find the search OpenBazaar experience sub-par, and feel alienated.

Thoughts?

**Comment by drwasho** [comment]
Justin, the number of features and enhancements we have yet to implement is staggering. But, the completion deadline we have set for ourselves is finite. The resources we have are finite. The funding we have is finite. 

The perfect product will not be shipped. Accept this. Some features will have limited capability. Accept this. We are noting down what we need to improve in the future so we can circle back in future releases.

**Comment by hoffmabc** [comment]
Let's not make broad sweeping generalizations here. Search is not easy, agreed. I still don't see what the problem is with the basic search. Let's move past the fact that all the things that Justin mentioned take a pretty advanced level of expertise. I'll assume it was meant as no ill will considering no team has yet built anything like what we are building. Search across p2p has been notoriously shitty and we will have to iterate as we go. For now I think this will be fine. If users have a problem with the quality of search they are free to use alternatives...

**Comment by JustinDrake** [comment]
As it stands, the presence of the top bar is a strong visual invitation to use the search functionality provided. From a user interface perspective, you are implicitly vouching for basic search.

Time is limited, P2P search is shitty, and the reference client is about great user experience. So why not drop search? Should search be someone else's problem?

**Comment by drwasho** [comment]
Basic search with iterating functionality is what we decided to go for. If you find someone with expertise and time willing to help in that effort, please refer them to this issue. Otherwise, we'll iterate as we go.

**Comment by cpacia** [comment]
The big question this brings up going forward is do we need keyword search at all? If not, it pretty radically changes the networking code as we probably don't need our own dht and could use ipfs for everything.

**Comment by hoffmabc** [comment]
We need search. At this point in time there are not enough good discoverability options to not have it. Let's put a lid on this until we get the release out and start addressing it later.
