### ISSUE TITLE
Vendor needs ability to label items "Out of Stock" or "Inactive"

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#531]
Right now you can either display an item or delete an item, with nothing in between, but that's going to be a major problem for someone who runs out of stock temporarily.

@morebrownies suggests:

> Listings need some type of status field so that vendors can set them to `active` `out of stock` or `inactive`
> 
> They’ll need this for adding new items to their store too. They may want to preload listings and activate all of them on the same day when they’re ready.
> 
> [If someone lists as out of stock ] we could hide the buy buttton and display out of stock instead

**Comment by morebrownies** [comment]
It would be helpful if we could start adding screenshots of people asking for certain features so that when we take on the work we have a good idea of how important it is and what they're trying to accomplish. 

<img width="963" alt="screenshot 2016-01-29 10 58 25" src="https://cloud.githubusercontent.com/assets/13066886/12682056/3be531f6-c677-11e5-969e-78bbf95ebfeb.png">

**Comment by drwasho** [comment]
Similar to #1133, but an enhancement to build upon once we can count and reduce available stock after purchase.

**Comment by ghost** [comment]
Is it possible to attach a JSON variable to the listing (out_of_stock), and keep the client from buying it? If they buy it anyways (old version of the OB client), then refund the client and tell them to upgrade their version of OpenBazaar? Maybe withhold the public key for the wallet if they try to buy it instead of shafting the buyer with transaction fees.
