### ISSUE TITLE
Theme selection shouldn't be in the wizard

### ISSUE THREAD

**Issue by ripper234** [OpenBazaar/OpenBazaar-Client#569]
The wizard is already 10 steps long, removing steps will help conversion.

Start with a default theme and let the user switch themes after.

**Comment by morebrownies** [comment]
There are few things to consider here:

1) The user's GUID is generating in the background while they're working on onboarding. So if we focus purely eliminating steps for the sake of eliminating steps, the user will still have to wait on a loading screen. I'd much rather they be productive during this time, while they're motivated and excited about trying the application for the first time.

2) I'd prefer for users to set a theme from the start so that every page does not look the same.

3) Most of the steps only require the user to hit next. 

4) Less steps does not always correlate to a higher conversation rates. I've ran many experiments in the past that actually proved the opposite. If users are motivated and the steps are broken out into simple one question screens that require little or no thought, they will complete at a very high rate.

5) This isn't a sign up process, it's configuration. For example, launching a brand new computer requires many configuration steps to personalize the experience for you. Same goes for OpenBazaar.

**Comment by ripper234** [comment]
Most users will be buyers, no stores/sellers.
Why does a buyer care about a theme for his page?

**Comment by morebrownies** [comment]
We're planning on introducing features in the future that will enable buyers to become curators on the network. So basically anyone will be able to share / like items, build an audience, chat with others and drive viewers to their page.

**Comment by hoffmabc** [comment]
I think best course of action for now is to leave as is and we can adjust as necessary later on as we get feedback on the themes etc.

**Comment by hoffmabc** [comment]
Is one of them preselected @morebrownies? Maybe at a minimum we do that if not already?

**Comment by morebrownies** [comment]
One use to be preselected, but I think it may have been removed. Not sure why.

**Comment by morebrownies** [comment]
I'm going to close this for now. The positives of having this step in onboarding should outweigh the negatives. We can revisit at a later time if we notice users aren't completing the configuration process.
