### ISSUE TITLE
Add new listing type: "Requests" or "Wanted"

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#597]
The peer to peer and social nature of OB lends itself to more than just one-way trade (vendor to buyer). 

Users should be able to post requests or wanted ads. These requests could be for any of the existing three listing types.

I'm not sure how best for the person fulfilling the request should respond. Ideally it would be some type of private listing such as #187 suggests.

Opening this issue to prompt discussion on how best to implement this after v1 is out.

@morebrownies and @drwasho I would particularly like your input because I know you place emphasis on the social aspect of OB and I think this feature could really aid that development, especially if we combine it with location data.

**Comment by drwasho** [comment]
This is a good request, and it's been on my mind since the early days. Some quick thoughts:
- This is the 'invitation to tender' feature that I have written about in the past
- I think we need a different type of interface to submit, search and filter tenders that come in to a user's request (and we certainly need better language)
- I think this is also going to be related to curation of certain product categories or channels
  - For example, something cool about BitMessage is that you can have dedicated channels where only the subscribers of that channel can receive and broadcast messages

I'll keep thinking about this.

**Comment by morebrownies** [comment]
My quick thought on this feature is it touches almost every part of the application and there's a lot we need to consider to ensure we do not confuse the user:

1) We would need to reconsider how requests vs listings display on a user page, e.g. it wouldn't really make sense to have them in your "store" tab so we may have to introduce a new tab for them.
2) How does discover change to display both listings and requests? Again, new tab, a filter within the listings tab or something else? I'd have to think about this more...
3) How does the transactions section change? When someone funds my request, does that go into the purchases tab?
4) How does the search experience change? If i'm searching #rockMusic I wouldn't necessarily want to see both requests and listings. 
5) What does the request detail screen look like? We could probably reuse the listing detail screen to some extent, but we'd also want to differentiate them a bit.
6) How does the checkout process change?

There's a ton to consider and I think I'd want to go through a design sprint on this in the future to get a better idea if we could layer it in nicely.

**Comment by drwasho** [comment]
I'll flesh out this concept and post some thoughts here @morebrownies to help you with the design sprint. 

I'll try for later today or tomorrow.

**Comment by morebrownies** [comment]
No rush

**Comment by bitcoinuser** [comment]
+1 for stuff wanted feature. Something like this: https://www.gumtree.com/stuff-wanted

**Comment by jjeffryes** [comment]
This is on the roadmap for v2.
