### ISSUE TITLE
Show Moderators attached to a listing

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#599]
Applies for:
1. Creating a listing
2. Editing a listing
3. Browsing a listing after clicking it on the Store page or Discovery page

**Comment by drwasho** [comment]
This occurred to me when I was trying to purchase a contract and none of the new Moderators I had selected were attached to the listing. I realised I had to go into that listing and edit it in order to add the new Moderators I had selected.

**Comment by jjeffryes** [comment]
The tricky thing here is this would have to create a new contract, since any change to a contract creates a new one. 

I think what we'd need to do is every time you add (or remove) a moderator, we'd have to loop through all your contracts to change the moderators and then save them as new contracts. 

If we did that, I think it would be best as a backend operation that happens invisibly.

**Comment by drwasho** [comment]
Yep I agree.

On the front end side we'd need to see what Moderators are attached to individual listings.

**Comment by morebrownies** [comment]
Yes, agreed with @jjeffryes. The vendor is not going to want to have to manually check and update each contract every time time they add a new moderator, it should instead happen automatically behind the scenes. 

Can we close this issue @drwasho or move it to the server?

**Comment by drwasho** [comment]
No problem.
