### ISSUE TITLE
Purchase QR disappears

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#640]
The purchase QR code disappears if I don't pay first time round.

![screen shot 2016-02-01 at 15 57 45](https://cloud.githubusercontent.com/assets/731743/12720779/a0b0a93a-c8fc-11e5-9675-c70419a8ff14.png)

**Comment by morebrownies** [comment]
I'm not a fan of the unfunded purchases displaying in your Transactions section for a number of reasons:

1) The Purchases/Sales tabs imply finalized orders to me. 
2) I'm not sure this matches the user's expectations. When they're checking out and abandon the checkout modal, the idea of that unfunded transaction living on forever seems odd to me. 
3) I'm not sure anyone would think to check their transaction > purchases section to finalize an order they abandoned. If anything, they would be much more likely to go through the checkout process again on the vendor's page.
4) It's confusing to vendors. It will definitely be helpful to get a sense of how many users are abandoning orders, but that's more of a reporting thing that should eventually live somewhere else.

So imo the best way to fix this issue is by not even making it possible in the first place. When the user abandons the checkout modal, simply delete the transaction.

**Comment by jjeffryes** [comment]
I don't think we have a way to delete the transaction. Until we do, we'll need to give the user a way to complete an order, especially since they may think they're done before they send any bitcoins.

**Comment by jjeffryes** [comment]
Also, this was fixed a while ago.
