### ISSUE TITLE
Maximum number of concurrent chat discussions

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#652]
Duo Money is looking to have hundreds of concurrent encrypted chat discussions with buyers. How many concurrent encrypted chat discussions can the client handle?

**Comment by hoffmabc** [comment]
Do you mean in a performance type of way?

**Comment by JustinDrake** [comment]
I mean from a feasibility point of view. Can a single node realistically handle hundreds of concurrent discussions within the reference client? I expect large eBay stores have many concurrent discussions with their buyers, and wondered if OpenBazaar is designing the encrypted chat UI for these large sellers.

Things that from the top of my head could break when there are hundreds of chats:
- Bad performance
- Hardcoded maximum number of chat discussions
- The chats become unwieldy to navigate when there are too many, because they need to be manually scrolled through

**Comment by hoffmabc** [comment]
We can probably test that fairly easily.

**Comment by morebrownies** [comment]
From purely an interface point of view, I've designed Chat so that you can safely manage about 10 concurrent conversations at a given time. Anything beyond 10 active conversations typically is unmanageable by a single person anyways and will require a team of customer service reps to distribute the load to. 

There are limitations within the reference client. We simply cannot build one app to solve every problem for every user, but this creates amazing opportunities for 3rd party tools to emerge to make managing customer service easier for mid to large size stores. intercom.io for example does exactly this for traditional eCommerce stores and they employe 200+ people to solve these types of problems.

**Comment by hoffmabc** [comment]
At some point a dedicated view for chat conversations will probably be necessary and we have discussed this before.

**Comment by morebrownies** [comment]
Agreed, it could be useful. However, having a dedicated Chat view doesn't solve the distribution problems for mid to large size businesses though. If you have hundreds of inbound messages coming in every few minutes, you need many people to distribute the load to, a single person can't keep up with it. Simply adding a dedicated view doesn't solve any of the underlying problems for big businesses. They'll need user roles, ticketing, volume distribution, reporting, etc. It's not trivial.

**Comment by morebrownies** [comment]
@JustinDrake This should be answered.
