### ISSUE TITLE
Allow override of merchant shop styling for usability and aesthetic preference

### ISSUE THREAD

**Issue by Deku-shrub** [OpenBazaar/OpenBazaar-Client#664]
Currently merchants can use the templating system to pick from a variety of key colours for background, font etc.

This has the potential for merchants to pick poorly contrasting colours (e.g. black text on a black background) or simply something aesthetically displeasing for the user. (e.g all pink and magenta).

This is common challenge featured on Reddit with regards to subreddit styling. Mostly customisations are good - except where they're not.

As a result, the popular add-on 'reddit enhancement suite' creates a checkbox called 'enable subreddit style' which can be unchecked, reverting things to a set of defaults.

I would suggest such a feature for inclusion to protect against unusable or undesirable styles.

**Comment by hoffmabc** [comment]
I'm torn on this one because the merchant should have control of their branding. If they choose shitty colors then it's their loss. More customization is probably better but it's also important that merchants understand how their customers are viewing their marketplace.

**Comment by jjeffryes** [comment]
If the suggestion is to allow users to ignore vendor themes, and see everything in the default style, then I think that invalidates the purpose of allowing custom themes.

**Comment by morebrownies** [comment]
If you don't care for the branding/aesthetics of a company you probably wouldn't care to purchase from them. Hiding their branding so that you could purchase from them without seeing what they stand for seems a bit odd to me. 

I tried to design it so that vendors have to see their own color palette choices throughout their transactions and settings sections. I'm hoping this will motivate them to use colors that do not burn the retinas of their users eyes. :)
