### ISSUE TITLE
Menu Intermittently Not Working

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#678]
I have noticed from time to time the menu button (avatar) does not activate the drop down. It can be resolved by refreshing the app window.

**Comment by jjeffryes** [comment]
I've noticed this too. It's been happening for quite a while, I haven't been able to track it down or reliably reproduce it.

**Comment by morebrownies** [comment]
I've noticed this seems to happen mostly or primarily when using remote servers. After I make the initial connection to a remote server, the user nav doesn't seem to work.

**Comment by jjeffryes** [comment]
This may have been fixed. The main content div sometimes overlapped the nav bar when it loaded, despite it having a lower z-index, which was fixable by hitting the refresh button. 

I changed the order of the divs, and haven't seen the problem since, so keep an eye out for it to see if that did it or not.

**Comment by jjeffryes** [comment]
I believe this has been fixed now.
