### ISSUE TITLE
Criteria for centralised search engine inclusion

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#709]
I am working on a centralised search engine for OpenBazaar which will include filtering of 'undesired' listings such as illegal listings and listings with high scam probability. I will be using a manual approach to strike off listings initially. When we get data from the manual approach, I will train a machine learning model (using skills acquired during my applied machine learning PhD) to automatically filter listings. Errors made by the automated filterer will be corrected manually which will advise new rules for re-training.

Sam suggested that the team working on OpenBazaar may be interested in integrating a centralised search. I want to know what the team thinks are desirable properties or the minimum necessary criteria for inclusion into the OpenBazaar client.

**Comment by JustinDrake** [comment]
+1 Decentralised search's user experience is sub-standard. Some torrent clients have integrated centralised search. This is an important discussion to be had.

**Comment by morebrownies** [comment]
+1 Offering additional search sources within the client seems extremely valuable to me. There are a few things that stand out to me that we'll need to consider to ensure we nail the experience:
1. It should be opt-in and not pre-selected. The first time a user performs a search, we could trigger a modal to open and ask them which provider they would prefer to use. If they choose to stick with the built in search experience, that's completely fine, but they'll also have the ability to choose between 3rd party providers. 
2. Avoid lock in to a search provider. This one seems pretty obvious, but basically we'll need to add a search provider option in Settings that can be changed by the user at any time.
3. Allow for a custom endpoint url. If a user wishes to spin up their own search endpoint and use it within the client, they should be able to do so by entering in an endpoint url. 
4. We'll need to standardize the format search providers are required to deliver their results in so that the results plug in nicely to the client. Documentation will be needed here. I'll let the technical guys chime in more on what would be needed here.

**Problems I see / Questions I have**

**How can we maintain a high bar and ensure the user is protected?**
If anyone has the ability to submit their search endpoint to display as an option within the client, this opens the potential for abuse by leading users to sketchy listings. 

**How do we rank the providers?**
For Wallet providers, we chose to sort them randomly for now, which definitely makes for an equal playing ground across Wallet providers, but this may also lead to confusion on the user's end. In most cases, they'll probably choose a provider from the top few options, even though the best option may be at or near the bottom. I'm all for making things equal, but when the quality between providers is drastically different, I start to question if random is truly the best approach. 

**How does language/region come into play?**
There may be top notch search providers that specialize in serving english listings, but they struggle with other languages. When search provider options are presented to the user, we'll probably want to consider their region and display search providers that serve their language/region well.

After thinking through everything I wrote above, I'm start to question if providing a list of search provider options in client is even a good idea. It for one introduces a lot of maintenance, 2) it make us look like bad guys if we reject your option from displaying in the client and 3) the language/region challenge becomes pretty complicated. Maybe I'm overthinking this and instead of providing options in client, the client could simply allow the user to type in an endpoint to any provider they wish to use and that's it. 

Thoughts?

**Comment by Kirvx** [comment]
I think this one should be a required features for the v1.0, with a **strong** recommendation for the user.
Without that, we could see extremely disturbing things in the "Discover" menu...

> Allow for a custom endpoint url. If a user wishes to spin up their own search endpoint and use it within the client, they should be able to do so by entering in an endpoint url.

It should be deactivated by default with a warning if the user activates it in the settings.

> How do we rank the providers?

You can rate providers with a number of stars:

1 star  : Does not contain pornographic content.
2 stars: Does not contain pornographic and gun content.
3 stars: Does not contain pornographic, gun and drug content.

4 & 5 stars can be about the protection against scam.

Every providers must provide a full access to their listings.

> How does language/region come into play?

Any provider can ensure a foreign listing does not contain pornographic ,gun and drug content.
I think it is most the important.

**Comment by BazaarBay** [comment]
Sounds like a good list and exactly the stuff we've been talking and thinking about. I'm happy to hear more suggestions and comments.

**Comment by jjeffryes** [comment]
3rd party search will be part of v2.
