### ISSUE TITLE
Display Store Location in the World on User Page (optional)

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#722]

**Comment by ac225519** [comment]
Why is OpenBazaar using Google Maps ?
The functionality that is used is available from OpenStreetMaps / openlayers too.
http://openlayers.org/en/v3.13.1/examples/geolocation.html
http://openlayers.org/en/v3.13.1/examples/

**Comment by morebrownies** [comment]
We're not set on Google Maps. If someone wants to submit a pr with OpenMaps, I'm sure we would accept it, assuming it's working well of course.

**Comment by drwasho** [comment]
There's nothing wrong with Google maps, it's probably the best and most consumer friendly mapping system out there.

Anyway, the original issue was about displaying the Store Location in the User page, which I'm 100% behind... otherwise the user will find out via a failed order.

@morebrownies @jjeffryes @rmisio

**Comment by Stemby** [comment]
Instead of OpenLayers, [Leaflet](http://leafletjs.com/) might be a better/simpler solution (OSM itself is using Leaflet for the slippy map).

+1 for migrating from Google Maps to OpenStreetMap.

**Comment by rmisio** [comment]
@morebrownies how would this look design wise? Are we talking about adding a map somewhere on the About tab of the User page?

**Comment by drwasho** [comment]
@morebrownies this would be a good idea for 2.0

**Comment by jjeffryes** [comment]
We have decided not to do this.
