### ISSUE TITLE
'Enter' key to attempt connection

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#748]
In the welcome pane, where I enter my username and password, the 'Enter' key does nothing.

After I enter my credentials I expect the 'Enter' to be the equivalent of clicking 'Retry connection'.

![screen shot 2016-02-19 at 20 03 29](https://cloud.githubusercontent.com/assets/731743/13185906/da6cc604-d743-11e5-8c87-6598cb7cb0f5.png)

**Comment by drwasho** [comment]
That's because the Enter key could equally trigger the `Retry connection` or `Save Changes` button... so it does neither.

But, maybe if we moved the `Retry connection` button above the _Server Configuration_ header, then connecting the Enter button to `Save Changes` may work. 

What are your thoughts @morebrownies ?

**Comment by SamPatt** [comment]
@morebrownies or @jjeffryes Any updates on this?

**Comment by jjeffryes** [comment]
This is a low-priority feature that hasn't been added yet.

**Comment by ameliagoodman** [comment]
https://github.com/OpenBazaar/OpenBazaar-Client/pull/1806

**Comment by jjeffryes** [comment]
Closed by #1806.
