### ISSUE TITLE
If user does not have avatar display default avatar in all places

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#810]
As @hoffmabc brought up, onboarding looks strange with the empty box on the onboarding step. The same problem exists in settings as well:

<img width="898" alt="screenshot 2016-02-26 10 49 02" src="https://cloud.githubusercontent.com/assets/13066886/13358774/8fe23f50-dc76-11e5-93d4-149340f963c1.png">

Let's display the default avatar in both instances instead of the empty div.

**Comment by jjeffryes** [comment]
Something to be aware of: 

if we use the obvious solution of injecting the default image into that square, if they don't change it they will save that image and it will get a hash. The visual effect will be the same as when we show the default image for users that haven't uploaded anything, but instead of using the local default image, the client will think it's a real avatar and download it from that user's server, which will add to the amount of bandwidth used.

We should do something more complicated, and either show the default image so it appears to be in that box, but really isn't (probably by hiding the real box until you upload something, then hiding the fake box), or add logic to not save it unless they've selected a new image.

**Comment by morebrownies** [comment]
Agreed
