### ISSUE TITLE
Move home button over to the left of search input

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#83]
We talked about this already. Just a reminder.

**Comment by morebrownies** [comment]
Yes, this is for me.

**Comment by drwasho** [comment]
It used to be to the left, but now it's back on the right. I'm happy with it on the right actually, but whatever the consensus is.

**Comment by morebrownies** [comment]
I think we have two options:

1) We could keep it as is (back, forward, refresh, address bar, home, notifications, user)
2) Or move the refresh button into the address bar (like Safari) and then move the home button to the left  (back, forward, home, address bar (with refresh), notifications, user) http://i.imgur.com/WQFubLp.png

I'm kind of leaning towards #2 because it preserves space in the header and keeps the navigation page controls separate from the user controls.

**Comment by hoffmabc** [comment]
Looks like we're avoiding this one with the Discover button. I'm closing.
