### ISSUE TITLE
When an Order Changes Status, and it's Read Property is False, Indicate that In the UI

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#874]
We discussed this today. Add whenever convenient. 

<img width="1280" alt="screenshot 2016-03-01 08 59 27" src="https://cloud.githubusercontent.com/assets/13066886/13430791/175d41ec-df8c-11e5-9ab0-aeed1315158f.png">

**Comment by mariodian** [comment]
I made it in a way that when an action is required, the order has this orange indicator. I can make it for a new order only (ob.status == 0), but I think it makes little more sense the way I made it. Please let me know.

**Comment by morebrownies** [comment]
How do you define an action is required @mariodian ?

**Comment by mariodian** [comment]
These statuses inidicate some action was done, but it's yet to be finished:

0 - Purchasing
1 - Ready to process
2 - Confirmed/Shipped
4 - Disputed

On the other hand these statuses indicate no action is required from any party:

3 - Completed (payment released)
5 - Disputed closed
6 - Dispute resolved
7 - Refunded

**Comment by jjeffryes** [comment]
I have update the title. This issue, which was discussed offline, is a request to mark orders that have changed status since the last time they were opened. We are going to add a read property to the data returned from the api calls, when the status changes read will change to false, which will trigger the indicator. When the transaction is opened, a new api call will change the read status back to true.

The api changes have not been made yet.

**Comment by jjeffryes** [comment]
This was completed.
