### ISSUE TITLE
Show Network Errors in Status Bar

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#944]
Brief Description: 

When bad profiles or listings fail, show something in the status bar so what happened is clear, instead of just kicking the client back to the last history state, so the user understands what just happened.

**Comment by rmisio** [comment]
This is kind of done. On network errors (bad profiles, bad handles, etc...), the user won't just be kicked back to the previous page. A modal will show up with a message indicating the problem first, and then the user is kicked back.

If we want, we can put these errors in the status bar. But, is this really what we want? @morebrownies 
You may want to wait until https://github.com/OpenBazaar/OpenBazaar-Client/pull/977 is merged and see how the new Save Settings message looks. As I mentioned, we could style different types of messages differently.

**Comment by morebrownies** [comment]
The save settings experience is so minimal that it becomes easy to miss. When I hit save in my client, it takes about 20 seconds to complete the request and there isn't a loading indicator on the save button (when the request is processing).

As far as displaying error messages into the status bar goes, I think that may be a bit aggressive to present that amount of information in such a tight space, especially since it could easily be missed. If I try to connect to a page and it times out, I'd rather the error be front and center. I'm trying to dig up a design I had created for this in the past. I'll follow up and post it once I find it.

**Comment by rmisio** [comment]
ok.. the save settings behavior was updated based on a suggestion initiated by @drwasho :
https://github.com/OpenBazaar/OpenBazaar-Client/issues/959

I'm not sure what we want here... Should I leave the status bar message and add in a loading spinner on the button? Should I revert back to the modal error message (although that didn't include the loading spinner either)? Should I revert back to the modal error message and put in a loading spinner?

**Comment by morebrownies** [comment]
For now, I'd say we definitely need a spinner on the save button(s). I'm also going to play around with the styling of the status bar to see if I can make it a bit more prominent when it displays. 

Error messages I still think we're going to need to do something that is much more in your face and doesn't auto dismiss. Still trying to find the screenshot I was referencing, hold tight...

**Comment by morebrownies** [comment]
Here's the design for a failed connection I put together a while back. Currently, when you try to connect to an offline store there are a few UX problems that arise.

1) I can't stop the request once it has started. If it's hanging for a while, I'm stuck looking at a spinner. Ideally, the user would have a way to Stop/Cancel the request and immediately return back to where they were.
![openbazaar-failed-connection](https://cloud.githubusercontent.com/assets/13066886/13578399/53273392-e45d-11e5-8a38-84a70a6f7338.png)

2) When the connection does fail, we should explain to the user why the connection failed and give them controls to retry or return back to where they were. 
![openbazaar-failed-connection-retry](https://cloud.githubusercontent.com/assets/13066886/13578348/0da383c0-e45d-11e5-9198-bdffe42ce3ce.png)

**Some of the error use cases could be:**
The handle you entered is not connected to a page (Back | Retry)
The page you're trying to view is currently offline (Back | Retry)
The listing your'e trying to view is currently offline (Back | Retry)

I'd like to add tooltips to each of these and present more information on hover as well, e.g. "The reason you can't reach @themes is because the owner of the page has either taken their page offline or..."

**Comment by drwasho** [comment]
Completed.
