### ISSUE TITLE
No CountryCode value for other countries in Create Listing

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#95]
I just added Afghanistan to my shipping countries.

![image](https://cloud.githubusercontent.com/assets/45482/10741221/007e8bb8-7bfd-11e5-869b-f42c98f5abdb.png)

**Comment by jjeffryes** [comment]
Looks like Afghanistan is missing from countries.proto and countries.py.

**Comment by unsystemizer** [comment]
`ALLAND_ISLANDS` also has no country code

**Comment by jjeffryes** [comment]
@hoffmabc or @cpacia or @unsystemizer might be better for this one, it's a python file that needs to be changed.

**Comment by hoffmabc** [comment]
@cpacia can you fix this one please?

**Comment by cpacia** [comment]
I'll add them to the end of the list. It's too much of a pain to put them in their spot in alphabetical order and manually re-number everything. @jjeffryes your code might be missing them as well since I believe you just pasted what you had into the protobuf.

**Comment by jjeffryes** [comment]
I'll check, but I think the error happens when a country that is in the client is sent to the server.

This probably happened because I missed a couple countries when I translated the code from the client to the server. I did a bunch of regex to reformat it, I may have accidentally erased something.

**Comment by z3ntu** [comment]
bump, is it fixed?

**Comment by drwasho** [comment]
Fixed.
