### ISSUE TITLE
Best image fitting / aspect ratio

### ISSUE THREAD

**Issue by trashMeNow** [OpenBazaar/OpenBazaar-Client#954]
Brief Description: when insert image not squared, this is displayed with a not "perfect" aspect ratio

Operating System (OS and version): windows 7 64bit SP1
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: intel i7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. insert image on auction

Observed Behavior:it is cutted at the top/bottm

Expected Behavior: improve image fitting/cropping

Additional info (links, images, etc go here):
![error_1](https://cloud.githubusercontent.com/assets/9824947/13509593/9824be34-e18c-11e5-96a5-b6900625bc00.jpg)

**Comment by jjeffryes** [comment]
The current code centers the image and cuts off the overlap, since there's no automatic way to tell what the "best" place to crop an image is. For any given image, the important parts could be anywhere.

Our roadmap includes adding a more advanced image editor, with user controlled cropping and other tools. That will be included eventually in a future release.
